#pragma once

#include "SLRRow.h"

static const SLRTable slrRightPartTable = {
	CSLRRow({ { "(", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 1) }, { "-", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 2) }, { "const", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 3) }, { "left_part", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 7) }, { "A", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 4) }, { "B", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 5) }, { "S", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 6) } }),
	CSLRRow({ { "(", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 1) }, { "-", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 2) }, { "const", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 3) }, { "left_part", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 7) }, { "A", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 4) }, { "B", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 5) }, { "S", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 8) } }),
	CSLRRow({ { "(", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 9) }, { "left_part", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 10) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 9) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 9) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 9) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 9) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 2) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 11) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 2) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 2) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 4) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 4) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 4) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 4) } }),
	CSLRRow({ { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 12) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::ACCEPTED, 0) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 7) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 7) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 7) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 7) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 13) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 12) } }),
	CSLRRow({ { "(", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 1) }, { "-", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 2) }, { "const", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 3) }, { "left_part", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 7) }, { "A", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 4) }, { "B", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 5) }, { "S", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 14) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 8) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 8) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 8) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 8) } }),
	CSLRRow({ { "(", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 1) }, { "-", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 2) }, { "const", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 3) }, { "left_part", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 7) }, { "B", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 15) } }),
	CSLRRow({ { "(", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 1) }, { "-", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 2) }, { "const", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 3) }, { "left_part", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 7) }, { "A", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 16) }, { "B", CSLRRow::Action(CSLRRow::Action::ActionType::GOTO, 5) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 5) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 5) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 5) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 5) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 17) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 12) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 3) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 3) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 3) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 3) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 1) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::SHIFT, 11) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 1) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 1) } }),
	CSLRRow({ { ")", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 6) }, { "high_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 6) }, { "low_bin_op", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 6) }, { "EOLN", CSLRRow::Action(CSLRRow::Action::ActionType::REDUCE, 6) } })
};