#pragma once

#define MOVE_PARAM_DECL /*Means that value might be taken by class member from parameter*/

enum struct VarKind
{
	VAR,
	ARRAY,
	MAP_VAR
};

enum struct VarType
{
	TYPE_VOID,
	TYPE_INT,
	TYPE_CHAR,
	TYPE_FLOAT,
	TYPE_STRING
};

enum Labels
{
	START_CODE,
	END_CODE,
	FUNCTION_START,
	FUNCTION_END,
	FUNCTION_START_DECL,
	FUNCTION_END_DECL,
	FUNCTION_START_PARAM_LIST,
	FUNCTION_END_PARAM_LIST,
	FUNCTION_START_PARAM,
	FUNCTION_END_PARAM,
	START_EXPLIST,
	END_EXPLIST,
	START_DECL,
	END_DECL,
	START_ASSIGN,
	END_ASSIGN,
	START_INPUT,
	END_INPUT,
	START_OUTPUT,
	END_OUTPUT,
	START_WHILE,
	END_WHILE,
	START_FOR,
	END_FOR,
	START_CONDITION,
	END_CONDITION,
	START_IF,
	END_IF,
	START_ELSE,
	END_ELSE,
	START_RETURN,
	END_RETURN,
	START_VAR_DECL,
	END_VAR_DECL,
	START_ARITHMETIC_OPERATION,
	END_ARITHMETIC_OPERATION,
	START_COND_EXPR,
	END_COND_EXPR,
	START_ARRAY_FIRST_DIM,
	END_ARRAY_FIRST_DIM,
	START_ARRAY_SECOND_DIM,
	END_ARRAY_SECOND_DIM,
	START_MAP_DECL,
	END_MAP_DECL,
	START_FUNC_CALL,
	END_FUNC_CALL,
	START_FUNCTION_ARGUMENTS,
	END_FUNCTION_ARGUMENTS,
	START_FUNCTION_ARG,
	END_FUNCTION_ARG,
	START_FIRST_DIM,
	END_FIRST_DIM,
	START_SECOND_DIM,
	END_SECOND_DIM,
	START_VAR_DESRIBE,
	END_VAR_DESCRIBE,
	LABEL_NONE
};

enum struct Operator
{
	PLUS,
	MINUS,
	OR,
	MOD,
	MULT,
	DIV,
	UNARY_MINUS,
	AND,
	LOG_AND,
	LOG_OR,
	GREATER,
	LESS,
	EQUAl,
	NOT_EQUAL,
	GREATE_OR_EQUAL,
	LESS_OR_EQUAL
};