#pragma once
#include "RuleTable.h"
#include <string>

#define CRT CRuleTable
#define CRR CRuleRow

using namespace std;

static const vector<CRuleTable> grammarTable = {
	CRT({}),
	CRT({ CRR("code", { TokenType(17), TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 2) }, LEFT_NONTERMINAL),
	CRT({ CRR("func", { TokenType(17), TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 6) }),
	CRT({ CRR("other_code", { TokenType(17), TokenType(15), TokenType(10), TokenType(6), TokenType(12), }, 4) }, LAST_NONTERMINAL),
	CRT({ CRR("other_code", { TokenType(17), TokenType(15), TokenType(10), TokenType(6), TokenType(12), }, 5) }, LEFT_NONTERMINAL),
	CRT({ CRR("code", { TokenType(17), TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 1) }, LAST_NONTERMINAL),
	CRT({ CRR("func", { TokenType(17), TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 7) }, LEFT_NONTERMINAL),
	CRT({ CRR("return_type", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(17) }, 15) }),
	CRT({ CRR("id", { TokenType(1) }, 9) }, TERMINAL),
	CRT({ CRR("(", { TokenType(23) }, 10) }, TERMINAL),
	CRT({ CRR("idlist", { TokenType(24), TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 32) }),
	CRT({ CRR(")", { TokenType(24) }, 12) }, TERMINAL),
	CRT({ CRR("{", { TokenType(21) }, 13) }, TERMINAL),
	CRT({ CRR("explist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 41) }),
	CRT({ CRR("}", { TokenType(22) }, 0) }, TERMINAL),
	CRT({ CRR("return_type", { TokenType(17), }, 16), CRR("return_type", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 17) }, LEFT_NONTERMINAL),
	CRT({ CRR("void", { TokenType(17) }, 0) }, TERMINAL),
	CRT({ CRR("var_type", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 18) }, LAST_NONTERMINAL),
	CRT({ CRR("var_type", { TokenType(15), }, 19), CRR("var_type", { TokenType(10) }, 20), CRR("var_type", { TokenType(6) }, 21), CRR("var_type", { TokenType(12) }, 22) }, LEFT_NONTERMINAL),
	CRT({ CRR("int", { TokenType(15) }, 0) }, TERMINAL),
	CRT({ CRR("string", { TokenType(10) }, 0) }, TERMINAL),
	CRT({ CRR("char", { TokenType(6) }, 0) }, TERMINAL),
	CRT({ CRR("float", { TokenType(12) }, 0) }, TERMINAL),
	CRT({ CRR("id_decl", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 24) }, LEFT_NONTERMINAL),
	CRT({ CRR("var_type", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 18) }),
	CRT({ CRR("id", { TokenType(1) }, 26) }, TERMINAL),
	CRT({ CRR("array_decl", { TokenType(20), TokenType(39), TokenType(24), TokenType(19), TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(34), TokenType(35), TokenType(38), TokenType(46), TokenType(37), TokenType(36), TokenType(40), TokenType(41), TokenType(26), TokenType(25) }, 27) }, LAST_NONTERMINAL),
	CRT({ CRR("array_decl", { TokenType(20), TokenType(39), TokenType(24), TokenType(19), TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(34), TokenType(35), TokenType(38), TokenType(46), TokenType(37), TokenType(36), TokenType(40), TokenType(41), TokenType(26) }, 28), CRR("array_decl", { TokenType(25) }, 29) }, LEFT_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(20), TokenType(39), TokenType(24), TokenType(19), TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(34), TokenType(35), TokenType(38), TokenType(46), TokenType(37), TokenType(36), TokenType(40), TokenType(41), TokenType(26), TokenType(25) }, 0) }, EMPTY),
	CRT({ CRR("[", { TokenType(25) }, 30) }, TERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }),
	CRT({ CRR("]", { TokenType(26) }, 0) }, TERMINAL),
	CRT({ CRR("idlist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 33), CRR("idlist", { TokenType(24) }, 35) }, LEFT_NONTERMINAL),
	CRT({ CRR("id_decl", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 23) }),
	CRT({ CRR("other_decl", { TokenType(20), TokenType(24) }, 36) }, LAST_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(24) }, 0) }, EMPTY),
	CRT({ CRR("other_decl", { TokenType(20) }, 37), CRR("other_decl", { TokenType(24) }, 40) }, LEFT_NONTERMINAL),
	CRT({ CRR(",", { TokenType(20) }, 38) }, TERMINAL),
	CRT({ CRR("id_decl", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 23) }),
	CRT({ CRR("other_decl", { TokenType(20), TokenType(24) }, 36) }, LAST_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(24) }, 0) }, EMPTY),
	CRT({ CRR("explist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 42) }, LEFT_NONTERMINAL),
	CRT({ CRR("expression", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 47) }),
	CRT({ CRR("other_exp", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9), TokenType(22) }, 44) }, LAST_NONTERMINAL),
	CRT({ CRR("other_exp", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 45), CRR("other_exp", { TokenType(22) }, 46) }, LEFT_NONTERMINAL),
	CRT({ CRR("explist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 41) }),
	CRT({ CRR("empty", { TokenType(22) }, 0) }, EMPTY),
	CRT({ CRR("expression", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(9) }, 48), CRR("expression", { TokenType(1) }, 49), CRR("expression", { TokenType(7), TokenType(8) }, 50), CRR("expression", { TokenType(18), TokenType(13) }, 51), CRR("expression", { TokenType(14) }, 52), CRR("expression", { TokenType(16) }, 53) }, LEFT_NONTERMINAL),
	CRT({ CRR("decl_action", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(9) }, 54) }, LAST_NONTERMINAL),
	CRT({ CRR("op_action", { TokenType(1) }, 92) }, LAST_NONTERMINAL),
	CRT({ CRR("io_call", { TokenType(7), TokenType(8) }, 97) }, LAST_NONTERMINAL),
	CRT({ CRR("cycle", { TokenType(18), TokenType(13) }, 135) }, LAST_NONTERMINAL),
	CRT({ CRR("condition", { TokenType(14) }, 167) }, LAST_NONTERMINAL),
	CRT({ CRR("return_call", { TokenType(16) }, 131) }, LAST_NONTERMINAL),
	CRT({ CRR("decl_action", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(9) }, 55) }, LEFT_NONTERMINAL),
	CRT({ CRR("decl_left", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(9) }, 58) }),
	CRT({ CRR("decl_right", { TokenType(39), TokenType(19) }, 67) }),
	CRT({ CRR(";", { TokenType(19) }, 0) }, TERMINAL),
	CRT({ CRR("decl_left", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 59), CRR("decl_left", { TokenType(9) }, 60) }, LEFT_NONTERMINAL),
	CRT({ CRR("id_decl", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 23) }, LAST_NONTERMINAL),
	CRT({ CRR("map_decl", { TokenType(9) }, 61) }, LAST_NONTERMINAL),
	CRT({ CRR("map_decl", { TokenType(9) }, 62) }, LEFT_NONTERMINAL),
	CRT({ CRR("map", { TokenType(9) }, 63) }, TERMINAL),
	CRT({ CRR("<", { TokenType(34) }, 64) }, TERMINAL),
	CRT({ CRR("var_type", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 18) }),
	CRT({ CRR(">", { TokenType(35) }, 66) }, TERMINAL),
	CRT({ CRR("id", { TokenType(1) }, 0) }, TERMINAL),
	CRT({ CRR("decl_right", { TokenType(39) }, 196), CRR("decl_right", { TokenType(19) }, 69) }, LEFT_NONTERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }, LAST_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(19) }, 0) }, EMPTY),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 71) }, LEFT_NONTERMINAL),
	CRT({ CRR("all_left_parts", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 78) }),
	CRT({ CRR("rp", { TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(24), TokenType(26), TokenType(19) }, 73) }, LAST_NONTERMINAL),
	CRT({ CRR("rp", { TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32) }, 74), CRR("rp", { TokenType(24), TokenType(26), TokenType(19) }, 77) }, LEFT_NONTERMINAL),
	CRT({ CRR("bin_op", { TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32) }, 123) }),
	CRT({ CRR("all_left_parts", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 78) }),
	CRT({ CRR("rp", { TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(24), TokenType(26), TokenType(19) }, 73) }, LAST_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(24), TokenType(26), TokenType(19) }, 0) }, EMPTY),
	CRT({ CRR("all_left_parts", { TokenType(2), TokenType(3), TokenType(4), TokenType(5) }, 79), CRR("all_left_parts", { TokenType(23), TokenType(1), TokenType(29) }, 80) }, LEFT_NONTERMINAL),
	CRT({ CRR("const", { TokenType(2), TokenType(3), TokenType(4), TokenType(5) }, 0) }, TERMINAL),
	CRT({ CRR("complex_part", { TokenType(29), TokenType(23), TokenType(1) }, 81) }, LAST_NONTERMINAL),
	CRT({ CRR("complex_part", { TokenType(29), TokenType(23), TokenType(1) }, 82) }, LEFT_NONTERMINAL),
	CRT({ CRR("start", { TokenType(29), TokenType(23), TokenType(1) }, 84) }),
	CRT({ CRR("main_part", { TokenType(23), TokenType(1) }, 87) }, LAST_NONTERMINAL),
	CRT({ CRR("start", { TokenType(23), TokenType(1) }, 85), CRR("start", { TokenType(29) }, 86) }, LEFT_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(23), TokenType(1) }, 0) }, EMPTY),
	CRT({ CRR("-", { TokenType(29) }, 0) }, TERMINAL),
	CRT({ CRR("main_part", { TokenType(23) }, 88), CRR("main_part", { TokenType(1) }, 91) }, LEFT_NONTERMINAL),
	CRT({ CRR("(", { TokenType(23) }, 89) }, TERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }),
	CRT({ CRR(")", { TokenType(24) }, 0) }, TERMINAL),
	CRT({ CRR("left_part", { TokenType(1) }, 106) }, LAST_NONTERMINAL),
	CRT({ CRR("op_action", { TokenType(1) }, 93) }, LEFT_NONTERMINAL),
	CRT({ CRR("left_part", { TokenType(1) }, 106) }),
	CRT({ CRR("=", { TokenType(39) }, 95) }, TERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }),
	CRT({ CRR(";", { TokenType(19) }, 0) }, TERMINAL),
	CRT({ CRR("io_call", { TokenType(7) }, 98), CRR("io_call", { TokenType(8) }, 102) }, LEFT_NONTERMINAL),
	CRT({ CRR("cin", { TokenType(7) }, 99) }, TERMINAL),
	CRT({ CRR(">>", { TokenType(48) }, 100) }, TERMINAL),
	CRT({ CRR("left_part", { TokenType(1) }, 106) }),
	CRT({ CRR(";", { TokenType(19) }, 0) }, TERMINAL),
	CRT({ CRR("cout", { TokenType(8) }, 103) }, TERMINAL),
	CRT({ CRR("<<", { TokenType(47) }, 104) }, TERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }),
	CRT({ CRR(";", { TokenType(19) }, 0) }, TERMINAL),
	CRT({ CRR("left_part", { TokenType(1) }, 107) }, LEFT_NONTERMINAL),
	CRT({ CRR("id", { TokenType(1) }, 108) }, TERMINAL),
	CRT({ CRR("next_part", { TokenType(20), TokenType(39), TokenType(24), TokenType(19), TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(34), TokenType(35), TokenType(38), TokenType(46), TokenType(37), TokenType(36), TokenType(40), TokenType(41), TokenType(26), TokenType(25), TokenType(23) }, 109) }, LAST_NONTERMINAL),
	CRT({ CRR("next_part", { TokenType(23) }, 110), CRR("next_part", { TokenType(20), TokenType(39), TokenType(24), TokenType(19), TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(34), TokenType(35), TokenType(38), TokenType(46), TokenType(37), TokenType(36), TokenType(40), TokenType(41), TokenType(26), TokenType(25) }, 113) }, LEFT_NONTERMINAL),
	CRT({ CRR("(", { TokenType(23) }, 111) }, TERMINAL),
	CRT({ CRR("func_list", { TokenType(24), TokenType(1) }, 114) }),
	CRT({ CRR(")", { TokenType(24) }, 0) }, TERMINAL),
	CRT({ CRR("array_decl", { TokenType(20), TokenType(39), TokenType(24), TokenType(19), TokenType(28), TokenType(29), TokenType(30), TokenType(31), TokenType(42), TokenType(43), TokenType(32), TokenType(34), TokenType(35), TokenType(38), TokenType(46), TokenType(37), TokenType(36), TokenType(40), TokenType(41), TokenType(26), TokenType(25) }, 27) }, LAST_NONTERMINAL),
	CRT({ CRR("func_list", { TokenType(24) }, 115), CRR("func_list", { TokenType(1) }, 116) }, LEFT_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(24) }, 0) }, EMPTY),
	CRT({ CRR("left_part", { TokenType(1) }, 106) }),
	CRT({ CRR("other_func_list", { TokenType(24), TokenType(20) }, 118) }, LAST_NONTERMINAL),
	CRT({ CRR("other_func_list", { TokenType(24) }, 119), CRR("other_func_list", { TokenType(20) }, 120) }, LEFT_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(24) }, 0) }, EMPTY),
	CRT({ CRR(",", { TokenType(20) }, 121) }, TERMINAL),
	CRT({ CRR("left_part", { TokenType(1) }, 106) }),
	CRT({ CRR("other_func_list", { TokenType(24), TokenType(20) }, 118) }, LAST_NONTERMINAL),
	CRT({ CRR("bin_op", { TokenType(28) }, 124), CRR("bin_op", { TokenType(29) }, 125), CRR("bin_op", { TokenType(30) }, 126), CRR("bin_op", { TokenType(31) }, 127), CRR("bin_op", { TokenType(42) }, 128), CRR("bin_op", { TokenType(43) }, 129), CRR("bin_op", { TokenType(32) }, 130) }, LEFT_NONTERMINAL),
	CRT({ CRR("+", { TokenType(28) }, 0) }, TERMINAL),
	CRT({ CRR("-", { TokenType(29) }, 0) }, TERMINAL),
	CRT({ CRR("*", { TokenType(30) }, 0) }, TERMINAL),
	CRT({ CRR("/", { TokenType(31) }, 0) }, TERMINAL),
	CRT({ CRR("&", { TokenType(42) }, 0) }, TERMINAL),
	CRT({ CRR("|", { TokenType(43) }, 0) }, TERMINAL),
	CRT({ CRR("%", { TokenType(32) }, 0) }, TERMINAL),
	CRT({ CRR("return_call", { TokenType(16) }, 132) }, LEFT_NONTERMINAL),
	CRT({ CRR("return", { TokenType(16) }, 133) }, TERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }),
	CRT({ CRR(";", { TokenType(19) }, 0) }, TERMINAL),
	CRT({ CRR("cycle", { TokenType(18) }, 136), CRR("cycle", { TokenType(13) }, 143) }, LEFT_NONTERMINAL),
	CRT({ CRR("while", { TokenType(18) }, 137) }, TERMINAL),
	CRT({ CRR("(", { TokenType(23) }, 138) }, TERMINAL),
	CRT({ CRR("cond_expr", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1) }, 182) }),
	CRT({ CRR(")", { TokenType(24) }, 140) }, TERMINAL),
	CRT({ CRR("{", { TokenType(21) }, 141) }, TERMINAL),
	CRT({ CRR("explist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 41) }),
	CRT({ CRR("}", { TokenType(22) }, 0) }, TERMINAL),
	CRT({ CRR("for", { TokenType(13) }, 144) }, TERMINAL),
	CRT({ CRR("(", { TokenType(23) }, 145) }, TERMINAL),
	CRT({ CRR("id_decl", { TokenType(15), TokenType(10), TokenType(6), TokenType(12) }, 23) }),
	CRT({ CRR("=", { TokenType(39) }, 147) }, TERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }),
	CRT({ CRR(";", { TokenType(19) }, 149) }, TERMINAL),
	CRT({ CRR("cond_expr", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1) }, 182) }),
	CRT({ CRR(";", { TokenType(19) }, 151) }, TERMINAL),
	CRT({ CRR("id", { TokenType(1) }, 152) }, TERMINAL),
	CRT({ CRR("=", { TokenType(39) }, 153) }, TERMINAL),
	CRT({ CRR("right_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1), TokenType(29) }, 70) }),
	CRT({ CRR(")", { TokenType(24) }, 155) }, TERMINAL),
	CRT({ CRR("{", { TokenType(21) }, 156) }, TERMINAL),
	CRT({ CRR("explist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 41) }),
	CRT({ CRR("}", { TokenType(22) }, 0) }, TERMINAL),
	CRT({ CRR("cond_op", { TokenType(35) }, 159), CRR("cond_op", { TokenType(34) }, 160), CRR("cond_op", { TokenType(46) }, 161), CRR("cond_op", { TokenType(38) }, 162), CRR("cond_op", { TokenType(40) }, 163), CRR("cond_op", { TokenType(41) }, 164), CRR("cond_op", { TokenType(36) }, 165), CRR("cond_op", { TokenType(37) }, 166) }, LEFT_NONTERMINAL),
	CRT({ CRR(">", { TokenType(35) }, 0) }, TERMINAL),
	CRT({ CRR("<", { TokenType(34) }, 0) }, TERMINAL),
	CRT({ CRR("!=", { TokenType(46) }, 0) }, TERMINAL),
	CRT({ CRR("==", { TokenType(38) }, 0) }, TERMINAL),
	CRT({ CRR("&&", { TokenType(40) }, 0) }, TERMINAL),
	CRT({ CRR("||", { TokenType(41) }, 0) }, TERMINAL),
	CRT({ CRR("<=", { TokenType(36) }, 0) }, TERMINAL),
	CRT({ CRR(">=", { TokenType(37) }, 0) }, TERMINAL),
	CRT({ CRR("condition", { TokenType(14) }, 168) }, LEFT_NONTERMINAL),
	CRT({ CRR("if", { TokenType(14) }, 169) }, TERMINAL),
	CRT({ CRR("(", { TokenType(23) }, 170) }, TERMINAL),
	CRT({ CRR("cond_expr", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1) }, 182) }),
	CRT({ CRR(")", { TokenType(24) }, 172) }, TERMINAL),
	CRT({ CRR("{", { TokenType(21) }, 173) }, TERMINAL),
	CRT({ CRR("explist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 41) }),
	CRT({ CRR("}", { TokenType(22) }, 0) }, TERMINAL),
	CRT({ CRR("else", { TokenType(22), TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9), TokenType(11) }, 176) }, LAST_NONTERMINAL),
	CRT({ CRR("else", { TokenType(22), TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 177), CRR("else", { TokenType(11) }, 178) }, LEFT_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(22), TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9), }, 0) }, EMPTY),
	CRT({ CRR("else", { TokenType(11) }, 179) }, TERMINAL),
	CRT({ CRR("{", { TokenType(21) }, 180) }, TERMINAL),
	CRT({ CRR("explist", { TokenType(15), TokenType(10), TokenType(6), TokenType(12), TokenType(1), TokenType(7), TokenType(8), TokenType(18), TokenType(14), TokenType(13), TokenType(16), TokenType(9) }, 41) }),
	CRT({ CRR("}", { TokenType(22) }, 0) }, TERMINAL),
	CRT({ CRR("cond_expr", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1) }, 183) }, LEFT_NONTERMINAL),
	CRT({ CRR("cond_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1) }, 190) }),
	CRT({ CRR("ravage", { TokenType(35), TokenType(34), TokenType(46), TokenType(38), TokenType(40), TokenType(41), TokenType(36), TokenType(37), TokenType(24), TokenType(19) }, 185) }, LAST_NONTERMINAL),
	CRT({ CRR("ravage", { TokenType(35), TokenType(34), TokenType(46), TokenType(38), TokenType(40), TokenType(41), TokenType(36), TokenType(37) }, 186), CRR("ravage", { TokenType(24), TokenType(19) }, 189) }, LEFT_NONTERMINAL),
	CRT({ CRR("cond_op", { TokenType(35), TokenType(34), TokenType(46), TokenType(38), TokenType(40), TokenType(41), TokenType(36), TokenType(37) }, 158) }),
	CRT({ CRR("cond_part", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1) }, 190) }),
	CRT({ CRR("ravage", { TokenType(35), TokenType(34), TokenType(46), TokenType(38), TokenType(40), TokenType(41), TokenType(36), TokenType(37), TokenType(24), TokenType(19) }, 185) }, LAST_NONTERMINAL),
	CRT({ CRR("empty", { TokenType(24), TokenType(19) }, 0) }, EMPTY),
	CRT({ CRR("cond_part", { TokenType(23) }, 191), CRR("cond_part", { TokenType(2), TokenType(3), TokenType(4), TokenType(5) }, 194), CRR("cond_part", { TokenType(1) }, 195) }, LEFT_NONTERMINAL),
	CRT({ CRR("(", { TokenType(23) }, 192) }, TERMINAL),
	CRT({ CRR("cond_expr", { TokenType(23), TokenType(2), TokenType(3), TokenType(4), TokenType(5), TokenType(1) }, 182) }),
	CRT({ CRR(")", { TokenType(24) }, 0) }, TERMINAL),
	CRT({ CRR("const", { TokenType(2), TokenType(3), TokenType(4), TokenType(5) }, 0) }, TERMINAL),
	CRT({ CRR("left_part", { TokenType(1) }, 106) }, LAST_NONTERMINAL),
	CRT({ CRR("=", { TokenType(39) }, 68) }, TERMINAL)
};